### Update
POST https://api.github.com/repos/{{$dotenv GITHUB_ACCOUNT}}/{{$dotenv GITHUB_REPO}}/dispatches
Accept: application/vnd.github.v3+json
Authorization: token {{$dotenv GITHUB_TOKEN}}

{
  "event_type": "webhook test by vs code"
}


### Graphcms
POST {{$dotenv GRAPHCMS_ENDPOINT}}
Accept: application/json
Authorization: Bearer {{$dotenv GRAPHCMS_TOKEN}}

{
  "query": "{jpecPosts {id title image{url fileName mimeType} body{markdown html}} jpecPages {id title body{markdown html}}}"
}
