### Update
post https://api.github.com/repos/{{$dotenv GITHUB_ACCOUNT}}/{{$dotenv GITHUB_REPO}}/dispatches
#post https://api.github.com/repos/toyoakekaki/hugo-future-imperfect-slim-contentful/dispatches
Authorization: token {{$dotenv GITHUB_TOKEN}}
Accept: application/vnd.github.everest-preview+json

{
  "event_type": "webhook test by vs code"
}

### Graphcms
POST {{$dotenv GRAPHCMS_ENDPOINT}}
Accept: application/json
Authorization: Bearer {{$dotenv GRAPHCMS_TOKEN}}

{
  "query": "{jpecPosts {id title image{url fileName mimeType} body{markdown html}} jpecPages {id title body{markdown html}}}"
}
